### ISSUE TITLE
Eliminate plotting of gapped regions in line and dot plots

### ISSUE THREAD

**Issue by adingens** [dms-view/dms-view.github.io#108]
When the given sequential numbering has numerical gaps, the line plot plots a smooth line across the entire gap, which appears very similar to true data. The gap should not be plotted in the line plot, preferably without a gap even being shown in the line or dot plot.

**Comment by huddlej** [comment]
This is an example of the behavior described above:

![image](https://user-images.githubusercontent.com/85372/74498020-1dc81680-4e94-11ea-8cbf-97f315204602.png)

**Comment by skhilton** [comment]
Here is a possible solution https://observablehq.com/@d3/area-with-missing-data

**Comment by huddlej** [comment]
@skhilton After looking into this more, the approach you were taking on the [non-continuous-context-curve branch](https://github.com/dms-view/dms-view.github.io/commits/non-continuous-context-curve) was exactly what we needed to resolve this issue. I just pushed a commit that sorts the mocked up records you added with missing data into the observed data. This sorting resolves the interpolation issue like we want. For example, the display with HIV used to look like this:

![image](https://user-images.githubusercontent.com/85372/84564776-503a3100-ad19-11ea-9a13-8ad7ca96a00e.png)

And now it looks like this:

![image](https://user-images.githubusercontent.com/85372/84564778-55977b80-ad19-11ea-8e7f-36584b530a10.png)

Since that branch is so diverged from master now, we may want to create a new branch that cherry-picks the commits of interest or maybe rebase onto master. I think the commits we want are:

  - 932b4b3
  - 86def5f2
  - cbbd841
  - 625c634

We may want to revisit whether we can speed up the current implementation by only mocking up records with missing data at, for instance, the boundaries of each gap interval. I can look into this after performing the rebase/cherry-picking described above.
