### ISSUE TITLE
make default tool data match Lee et al paper data

### ISSUE THREAD

**Issue by jbloom** [dms-view/dms-view.github.io#126]
@skhilton: We should make the default data shown by the `dms-view` tool match the data shown in the Lee et al paper.

These data are the positive differential selection (site level) and positive differential selection (mutation level).

Right now you have absolute differential selection at site level, and both positive and negative for mutation level.

**Comment by skhilton** [comment]
closed with PR #128

**Comment by jbloom** [comment]
@skhilton: I'm re-opening this issue. I think we should make the default data shown when someone goes to [dms-view.github.io](https://dms-view.github.io/) match the data shown in the Lee et al paper.

Right now, it doesn't do that. Just to clarify, in the paper the data shown are the *positive* differential selection at both the site and mutation level. The default data shown in the website are the total at both site and mutation level, not the positive.

**Comment by skhilton** [comment]
@jbloom: Oh, I see. When I changed it, I did it for the case studies. I didn't realize you meant for the regular website. Sorry. I will change this.

**Comment by skhilton** [comment]
@jbloom: The site (dms-view.github.io) should now show positive differential selection for both site metric and the mutation metric on default. 

This was done by simply reordering the columns. The dropdown menus are populated in order of the columns. Do you think this is worth putting in the docs? It seems like no because you can just specify this in the URL.

**Comment by jbloom** [comment]
I think since you can specify in URL it's not worth adding to docs. Unless you think otherwise.

I'm OK with closing this issue if you think resolved.
