### ISSUE TITLE
ability to add arbitrary text metadata / explanations

### ISSUE THREAD

**Issue by jbloom** [dms-view/dms-view.github.io#87]
I'm raising this based on instructions @skhilton sent me. I am working to get some nCoV Spike evolutionary data in a suitable form for `dms-view`.

If we do that, we'll need one thing: the ability to add text that shows up somewhere (top or bottom) of page. This would be helpful for providing a brief explanation of what is shown and (crucially if we put anything for nCoV) providing acknowledgments as we'd need to acknowledge source of sequences.

**Comment by skhilton** [comment]
@jbloom: This issue is related to issue #3. 

There are two ways forward on this, an immediate but unsatisfactory solution or a long-term solution. The immediate solution I can show you how to edit the `html` document itself to add this information. If you go to the current website (jbloomlab.github.io/dms-view) you can see that we have a small write-up of Juhye's experiment (and related title) which we could change for your specific use case. 

The more long-term solution is described in @huddlej's write up of issue #3. We haven't even started working on this so it would be a day or two before that is implemented (I would guess).

**Comment by jbloom** [comment]
Okay, no rush. I think it is going to take several days to get food structural alignments data anyway

**Comment by huddlej** [comment]
This has been resolved by PR #106.
